name: "🛠 Help with Implementation"

# Triggers the workflow when a `needs-work` label is added to an issue or PR
on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  help-with-implementation:
    runs-on: ubuntu-latest
    if: "github.event.label.name == 'needs-work'"
    steps:
      - name: Assist with Implementation
        uses: PR-Pilot-AI/smart-actions/quick-task@v1
        with:
          api-key: ${{ secrets.PR_PILOT_API_KEY }}
          agent-instructions: |
            1. Read the ${{ github.event_name == 'issues' ? 'issue' : 'pull request' }} with ID `${{ github.event_name == 'issues' ? github.event.issue.number : github.event.pull_request.number }}`.
            2. Understand what needs to be worked on by analyzing the ${{ github.event_name == 'issues' ? 'issue' : 'pull request' }} description.
            3. Search the codebase for files related to the ${{ github.event_name == 'issues' ? 'issue' : 'pull request' }}.
            4. Read the identified files.
            5. Write the necessary changes to the files based on the ${{ github.event_name == 'issues' ? 'issue' : 'pull request' }} requirements.
            6. Commit the changes with a message that includes the ${{ github.event_name == 'issues' ? 'issue' : 'pull request' }} ID and a brief description of the work done.
