name: "🛠 Help with Implementation"

# Triggers the workflow when a `needs-work` label is added to an issue or PR
on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  help-with-implementation:
    runs-on: ubuntu-latest
    if: "github.event.label.name == 'needs-work'"
    steps:
      - name: Set Env Vars
        run: |
          echo "EVENT_TYPE=${{ github.event_name == 'pull_request' ? 'pull request' : 'issue' }}" >> $GITHUB_ENV
          echo "EVENT_ID=${{ github.event_name == 'pull_request' ? github.event.pull_request.number : github.event.issue.number }}" >> $GITHUB_ENV
      - name: Assist with Implementation
        uses: PR-Pilot-AI/smart-actions/quick-task@v1
        with:
          api-key: ${{ secrets.PR_PILOT_API_KEY }}
          agent-instructions: |
            1. Read the ${{ env.EVENT_TYPE }} with ID `${{ env.EVENT_ID }}`.
            2. Understand what needs to be worked on by analyzing the ${{ env.EVENT_TYPE }} description.
            3. Search the codebase for files related to the ${{ env.EVENT_TYPE }}.
            4. Read the identified files.
            5. Write the necessary changes to the files based on the ${{ env.EVENT_TYPE }} requirements.
            6. Commit the changes with a message that includes the ${{ env.EVENT_TYPE }} ID and a brief description of the work done.
