name: "🚀 Initialize Project"

on:
  workflow_dispatch:
    inputs:
      programming-language:
        description: 'The programming language of the project.'
        required: true
      framework:
        description: 'The framework to be used (optional).'
        required: false
      project-description:
        description: 'A brief description of the project.'
        required: true

jobs:
  setup_project:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Project Instructions
        uses: PR-Pilot-AI/smart-actions/quick-task@v1
        with:
          api-key: ${{ secrets.PR_PILOT_API_KEY }}
          agent-instructions: |
            This is an empty project and we want to initialize it.

            Programming language: ${{ github.event.inputs.programming-language }}
            Framework (optional): ${{ github.event.inputs.framework }}
            Project description:
            ${{ github.event.inputs.project-description }}
            
            1. Use the programming language and framework (if provided) to search the internet for information on how to start a project with these specifications.
            2. Search the internet to find the latest version of the language and framework
            3. Compile the information into a list of initial files that need to be created.
            4. Create a Github issue in the repository with the list of files to create, including a description of the content for each file and the label `needs-work`
            5. Make sure the issue mentions the need to create a README file for the new project
            6. Make sure the issue contains instructions to create a `TODO.md`, which should give some context and contains a checklist of next steps to implement the project
            
