name: "📋 Work on TODO List"

on:
  push:
    paths:
      - 'TODO.md'
    branches:
      - main

jobs:
  work-on-todo-list:
    runs-on: ubuntu-latest
    steps:
      - name: Work on Next TODO Item
        uses: PR-Pilot-AI/smart-actions/quick-task@v1
        with:
          api-key: ${{ secrets.PR_PILOT_API_KEY }}
          agent-instructions: |
            1. Read `TODO.md`
            2. Identify the next open item on the TODO list. If there is no open item, delete the file
            3. Fulfill the identified task to the best of your abilities.
            4. Edit `TODO.md` to mark the item you worked on as checked

            When fulfilling the task:
            - Make sure you have enough context by reading relevant files
            - If files you need do not exist, write them
